package io.github.bbstilson.model

object AwsEnvVar extends Enumeration {
  type AwsEnvVar = Value

  val AWS_LAMBDA_BUCKET_ID, AWS_LAMBDA_S3_KEY_PREFIX, AWS_LAMBDA_NAME, AWS_LAMBDA_HANDLER_NAME,
    AWS_LAMBDA_IAM_ROLE_ARN, AWS_REGION, AWS_LAMBDA_TIMEOUT, AWS_LAMBDA_MEMORY,
    AWS_LAMBDA_DEPLOY_METHOD, AWS_LAMBDA_DEAD_LETTER_ARN, AWS_LAMBDA_VPC_CONFIG_SUBNET_IDS,
    AWS_LAMBDA_VPC_CONFIG_SECURITY_GROUP_IDS = Value
}
